language: go
go: 
 - 1.9.4 
 - release
 - tip
 
script: 
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      script: 
        - make dep
        - make test
    - stage: build
      script: 
        - make binaries